language: c
install:
  - wget http://packages.madhouse-project.org/debian/add-release.sh
  - chmod +x add-release.sh
  - sudo ./add-release.sh syslog-ng-3.5
  - sudo apt-get update -qq
  - sudo apt-get install -qq pkg-config flex bison liblua5.2-dev libmongo-client-dev syslog-ng-dev
before_script:
  - autoreconf -i
script:
  - ./configure --enable-silent-rules
  - make distcheck
compiler:
  - gcc
  - clang
notifications:
  irc:
    channels:
      - "irc.freenode.org#balabit"
